---

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add ubuntu apt repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: APT update
  apt:
    update_cache: yes

- name: ZFS install
  apt: name={{ item }} state=latest
  with_items:
    - zfs

- name: Check if ZFS pool exist
  shell: zpool list -H|grep {{ docker_zfs_pool_name }}
  register: zpool_exist
  # ignore_errors: yes
  failed_when: false
  changed_when: False

- name: Create ZFS pool
  shell: zpool create -f -O compression=lz4 {{ docker_zfs_pool_name }} {{ docker_zfs_block_device_path }} 
  register: zpool_created
  when: zpool_exist.stdout == ""

- name: Create ZFS filesystems for docker
  zfs:
    name: "{{ docker_zfs_pool_name }}/{{ docker_zfs_vol_name }}"
    state: present
    mountpoint: /var/lib/docker
    compression: lz4
  when: zpool_created

- name: Create dir for docker daemon
  file: path=/etc/docker/  state=directory owner=root group=root mode=755

- name: Create docker config
  copy: src=etc/docker/daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=644 

- name: Install docker-ce
  apt: name={{ item }}
  with_items:
    - "docker-ce={{ docker_version }}~ce-0~ubuntu"

- name: Install dockers-compose package
  pip: name=docker-compose version={{ docker_compose_version }}  state=present

- name: Create default stratus network
  docker_network:
    name: stratus_default
    appends: yes
