---

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add ubuntu apt repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: APT update
  apt:
    update_cache: yes

- name: ZFS install
  apt: name={{ item }} state=latest
  with_items:
    - zfs

- name: Create ZFS pool & filesystems for docker
  shell: zpool create -f {{ docker_zfs_pool_name }} /dev/sdc \
        && zfs create {{ docker_zfs_pool_name }}/{{ docker_zfs_vol_name }} \
        && zfs set mountpoint=/var/lib/docker {{ docker_zfs_pool_name }}/{{ docker_zfs_vol_name }}

- name: Create dir for docker daemon
  file: path=/etc/docker/  state=directory owner=root group=root mode=755

- name: Create docker config
  copy: src=etc/docker/daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=644 

- name: Install docker-ce
  apt: name={{ item }}
  with_items:
    - "docker-ce={{ docker_version }}~ce-0~ubuntu"

- name: Install dockers-compose package
  pip: name=docker-compose version={{ docker_compose_version }}  state=present