---

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add ubuntu apt repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# - name: Add Zfs on Linux Repository
#   apt_repository: repo='ppa:zfs-native/stable' state=present

# - name: Apt update
#   shell: apt-get update && apt install -y docker-ce=17.06.2{{}}~ce-0~ubuntu

- name: APT update
  apt:
    update_cache: yes

- name: ZFS install
  apt: name={{ item }} state=latest
  with_items:
    - zfs
- name: Create ZFS pool
  shell: zpool create -f {{ docker_zfs_pool_name }} -m /var/lib/docker /dev/sdc

- name: Create dir for docker daemon
  file: path=/etc/docker/  state=directory owner=root group=root mode=755

- name: Create docker config
  copy: src=etc/docker/daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=644 

- name: Install docker-ce
  apt: name={{ item }}
  with_items:
    - "docker-ce={{ docker_version }}~ce-0~ubuntu"
