---
prometheus_docker_compose_path: /opt/docker-compose/infrastructure/prometheus
prometheus_docker_volume_cfg_path: /var/lib/docker/volumes/prometheus_cfg
prometheus_docker_volume_path: /var/lib/docker/volumes/prometheus_data
prometheus_docker_volume_cfg_name: 'prometheus_cfg'
prometheus_docker_volume_name: 'prometheus_data'
prometheus_scrape_interval: '15s'
prometheus_evaluation_interval: '15s'
prometheus_attach_label_monitor: 'stratus_mon'
prometheus_alert_manager_target: 'localhost:9093'
prometheus_rules_path: '/etc/prometheus/*.rules'
