---
- name: Create initial gogs database
  command: docker exec -i postgres /backups/initial_data_loader.sh

- name: Deploy gogs docker project
  docker_service:
    pull: yes
    project_name: gogs
    project_src: "{{ gogs_docker_compose_path }}"
